version: '3.8'

services:
  inngest:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - EVENT_KEY=b8bc74f7312cb8653fa453ea2b643632
      - SIGNING_KEY=923edcd52964f681533cb857ac2a70a983b57079fdd541fd876fde8e42d78f7c
      - REDIS_URI=redis://redis:6379
      - INNGEST_DEV=0  
    ports:
      - "8288:8288"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - inngest-db:/usr/src/app/.inngest

volumes:
  redis-data:
  inngest-db:
