version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - nginx-net
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

  inngest:
    image: inngest-image
    environment:
      - EVENT_KEY=b8bc74f7312cb8653fa453ea2b643632
      - SIGNING_KEY=923edcd52964f681533cb857ac2a70a983b57079fdd541fd876fde8e42d78f7c
      - REDIS_URI=redis://redis:6379
      - INNGEST_DEV=0
    networks:
      - nginx-net
    volumes:
      - inngest-data:/usr/src/app/.inngest  # Adjust the path if needed for inngest data storage

  redis:
    image: redis:latest
    networks:
      - nginx-net
    deploy:
      replicas: 1
    volumes:
      - redis-data:/data

networks:
  nginx-net:
    driver: overlay

volumes:
  redis-data:
    driver: local  # Change to appropriate driver if using cloud storage or other persistent options
  inngest-data:
    driver: local
