version: "3.8"

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy-net
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M

  redis:
    image: redis:latest
    networks:
      - caddy-net
    deploy:
      replicas: 1
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  inngest:
    image: inngest-image
    environment:
      EVENT_KEY: b8bc74f7312cb8653fa453ea2b643632
      SIGNING_KEY: 923edcd52964f681533cb857ac2a70a983b57079fdd541fd876fde8e42d78f7c
      REDIS_URI: redis://redis:6379
      INNGEST_DEV: "0"
    networks:
      - caddy-net
    volumes:
      - inngest-data:/usr/src/app/.inngest
    depends_on:
      - redis

networks:
  caddy-net:
    driver: overlay

volumes:
  redis-data:
  inngest-data:
  caddy_data:
  caddy_config:
